# Generated by Django 4.1.3 on 2022-12-09 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beauty_salon', '0002_orderline_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('photo', models.ImageField(upload_to='gallery/photos', verbose_name='photo')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to=settings.AUTH_USER_MODEL, verbose_name='master')),
            ],
            options={
                'ordering': ('master', '-created_at'),
            },
        ),
    ]
