# Generated by Django 4.1.3 on 2022-12-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0004_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='master',
            new_name='user',
        ),
    ]
